### ISSUE TITLE
Issue building pyramids with multiple stitching vectors

### ISSUE THREAD

**Issue by Nicholas-Schaub** [usnistgov/WIPP-pyramid-plugin#2]
A WIPP stitching vector can contain multiple stitching vector files. When this plugin is used to build a pyramid from a stitching vector containing multiple vector files, the resulting pyramid cannot be viewed using the built in WDZT viewer.

I ran into this issue when I used to generate a stitching vector using MIST using a file name expression that included timepoint. I could successfully build the images using the image assembly plugin, and the pyramid building plugin also completed successfully but could not be viewed in WDZT.

Here is a screenshot of WDZT when trying to view the pyramid:
![image](https://user-images.githubusercontent.com/15925882/68490885-c7ee2d80-0217-11ea-80b1-6168ac09177d.png)

**Comment by MyleneSimon** [comment]
After investigation, the bug is coming from WIPP-frontend, some http parameters are not properly handled for some of the requests used during the pyramid manifest generation, causing the manifest to have an incorrect value for `framesOffset` and WDZT to be looking for a first frame `000` instead of `001`. I will push a fix today, and we will probably push a hotfix for WIPP 3.0.0-beta.
